export enum MusclesInvolved {
    Abdominals = "Abdominals",
    Abductors = "Abductors",
    Adductors = "Adductors",
    Biceps = "Biceps",
    Calves = "Calves",
    Chest = "Chest",
    Forearms = "Forearms",
    Glutes = "Glutes",
    Hamstrings = "Hamstrings",
    Lats = "Lats",
    Lower_back = "Lower_back",
    Middle_back = "Middle_back",
    Neck = "Neck",
    Quadriceps = "Quadriceps",
    Traps = "Traps",
    Triceps = "Triceps",
    Anterior_deltoid = "Anterior_deltoid",
    Medial_deltoid = "Medial_deltoid",
    Posterior_deltoid = "Posterior_deltoid"
}