export enum MusclesInvolved {
    Abdominals = "Abdominals",
    Abductors = "Abductors",
    Adductors = "Adductors",
    Biceps = "Biceps",
    Calves = "Calves",
    Pectoralis_major = "Pectoralis_major",
    Pectoralis_minor = "Pectoralis_minor",
    Serratus_anterior = "Serratus_anterior",
    Forearms = "Forearms",
    Glutes = "Glutes",
    Hamstrings = "Hamstrings",
    Lats = "Lats",
    Lower_back = "Lower_back",
    Middle_back = "Middle_back",
    Upper_back = "Upper_back",
    Neck = "Neck",
    Quadriceps = "Quadriceps",
    Traps = "Traps",
    Triceps = "Triceps",
    Anterior_deltoid = "Anterior_deltoid",
    Medial_deltoid = "Medial_deltoid",
    Posterior_deltoid = "Posterior_deltoid",
    Bicycle = "Bicycle",
    Elliptical = "Elliptical",
    Treadmill = "Treadmill"
}