export enum MusclesInvolved {
    Abdominals = "Abdominals",
    Obliques = "Obliques",
    Abductors = "Abductors",
    Adductors = "Adductors",
    Biceps = "Biceps",
    Calves = "Calves",
    Upper_chest = "Upper_chest",
    Middle_chest = "Middle_chest",
    Lower_chest = "Lower_chest",
    Serratus_anterior = "Serratus_anterior",
    Forearms = "Forearms",
    Glutes = "Glutes",
    Hamstrings = "Hamstrings",
    Lats = "Lats",
    Lower_back = "Lower_back",
    Middle_back = "Middle_back",
    Upper_back = "Upper_back",
    Neck = "Neck",
    Quadriceps = "Quadriceps",
    Traps = "Traps",
    Triceps = "Triceps",
    Anterior_deltoid = "Anterior_deltoid",
    Medial_deltoid = "Medial_deltoid",
    Posterior_deltoid = "Posterior_deltoid",
    Lungs = "Lungs",
    Heart = "Heart",
}